### ISSUE TITLE
Add ability to increment package version (patch)

### ISSUE THREAD

**Issue by uniquelau** [edd-london/eslint-config-react#4]
Currently there are commands to increment by major and minor.

However, patch is missing.

Read over the specification for conventional commits, and how this ties in with semantic versioning (semver).

As an example, a `fix` should be a patch.

When we do release, we should follow the conventional commit format, perhaps:

`chore: release v1.0.7`

and also tag the commit `v1.0.7`

**Comment by gman112** [comment]
I have added a feat to include patch
